/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for a complete GrokBot (roleplay chatbot) profile. Optimized for LLM consistency through clear separation of behavioral rules, persistent facts (anchors), conditional triggers, and fixed-slot dialog examples. Fields are structured to support logical prompt export order while reducing drift and enabling variant overrides.
 */
export interface GrokBotProfile {
  /**
   * Schema version stamp written on save (e.g., '2'). Absent on v1 files — treat absence as v1.
   */
  schema_version?: string;
  /**
   * Unique identifier for the bot (UUID recommended). Used for stable referencing and overrides.
   */
  id: string;
  /**
   * Creator or collection ID (optional, for grouping bots).
   */
  cid?: string;
  /**
   * Display name of the bot/scenario.
   */
  name: string;
  /**
   * Creator-only notes/hints for using or sharing the bot (e.g., recommended user style, RP tips). Excluded from prompt export to avoid LLM confusion.
   */
  usage_hints?: string;
  /**
   * ISO timestamp of last edit.
   */
  lastModified: string;
  /**
   * Long-form internal description/premise of the bot (shown in cards, not sent to LLM).
   */
  intro: string;
  /**
   * The very first message the bot sends to start the chat.
   */
  greeting: string;
  /**
   * Core persistent roleplay behavioral rules and guidelines (e.g., perspective limits, godmodding prevention, pacing, output format). Placed very early in the exported prompt for strongest LLM adherence. Use neutral, imperative phrasing.
   */
  rp_rules?: string[];
  /**
   * World and scenario definition.
   */
  background?: {
    /**
     * Persistent, always-true world/plot facts that must never be forgotten (including hidden information unknown to characters). Placed early after rp_rules in prompt. Use declarative sentences.
     */
    anchors?: string[];
    /**
     * Global conditional guidance for plot progression, reactions, or revelations. Phrased naturally as 'If/When/Should X, then Y' statements. Relies on LLM reasoning — no regex or runtime matching.
     */
    triggers?: string[];
    /**
     * Physical and atmospheric world details.
     */
    setting?: {
      /**
       * Where the story takes place (places, era, etc.).
       */
      location?: string;
      /**
       * Overall mood/atmosphere.
       */
      environment_tone?: string;
      /**
       * Level of realism and any custom rules.
       */
      realism?: string;
      /**
       * Historical period or time setting.
       */
      era?: string;
      /**
       * City, region, or named world area.
       */
      city?: string;
      /**
       * Scene-level starting location within the city/world.
       */
      specific_location?: string;
      /**
       * Socioeconomic context, daily rhythms, or cultural backdrop.
       */
      lifestyle?: string;
    };
    /**
     * Plot premise and current state.
     */
    scenario?: {
      /**
       * Core concept or setup.
       */
      premise?: string;
      /**
       * Current events or conflicts.
       */
      ongoing_dynamic?: string;
      /**
       * User's initial role/position.
       */
      starting_state_with_user?: string;
    };
    /**
     * Supporting cast — named NPCs or recurring background figures.
     */
    cohorts?: CohortEntry[];
    /**
     * Keyword-keyed world facts for LLM recall.
     */
    lorebook?: LorbookEntry[];
    /**
     * The cast of characters. Full profiles embedded for self-contained bots.
     * May be empty if the scenario relies entirely on cohorts.
     */
    characters?: CharacterProfile[];
    /**
     * Global content safety/scope restrictions.
     */
    boundaries?: {
      /**
       * Explicitly permitted topics/elements (rarely needed).
       */
      allowed?: string[];
      /**
       * Strictly forbidden topics/elements.
       */
      disallowed?: string[];
    };
    /**
     * Technical RP rules.
     */
    meta?: {
      /**
       * How to handle OOC/meta comments.
       */
      fourth_wall_behavior?: string;
      /**
       * Additional persistence notes (supplements rp_rules).
       */
      continuity_rules?: string;
    };
  };
  /**
   * Publishing status of the bot.
   */
  status?: 'unpublished' | 'public' | 'unlisted';
  /**
   * @deprecated Use `status` instead. Kept for backward compatibility.
   */
  flags?: string[];
  /**
   * Filenames of images stored in the bot's dedicated image folder.
   */
  images?: string[];
  /**
   * Filename of the selected profile picture (optional).
   */
  profileImage?: string;
  /**
   * Number of images attached.
   */
  imagesCount?: number;
  /**
   * Local URL to image.
   */
  profileUrl?: string;
  /**
   * Variant-specific overrides. Each variant overlays the base independently.
   */
  variants?: {
    [k: string]: OverrideBlock;
  };
}
/**
 * Full character profile. Optimized for LLM voice consistency.
 */
export interface CharacterProfile {
  /**
   * Unique UUID for stable overrides/referencing.
   */
  id: string;
  /**
   * Short display name.
   */
  name: string;
  /**
   * Optional full/legal name.
   */
  full_name?: string;
  /**
   * Common nickname or shortened name used in casual address.
   */
  nickname?: string;
  /**
   * Single-label narrative archetype (e.g., 'The Obsessive Protector').
   */
  archetype?: string;
  /**
   * Character age (18+ for adult bots).
   */
  age?: number;
  /**
   * Gender identity.
   */
  gender?: string;
  /**
   * Sexual/romantic orientation (factual identity).
   */
  orientation?: string;
  /**
   * Role in story (e.g., protagonist's sister, rival).
   */
  role?: string;
  /**
   * One-paragraph summary/vibe.
   */
  overview?: string;
  lastModified: string;
  appearance?: AppearanceBlock;
  personality?: PersonalityBlock;
  /**
   * Detailed history (foundation for motivations/behavior).
   */
  backstory?: string;
  /**
   * Specific known relationships (NPCs or other characters).
   */
  relationships?: RelationshipBlock[];
  skills?: SkillsBlock;
  story_hooks?: StoryHooksBlock;
  behavior_rules?: BehaviorRulesBlock;
  /**
   * Character-specific persistent roleplay behavioral rules (e.g., speech limits, pacing preferences). Supplements global rp_rules.
   */
  character_rp_rules?: string[];
  /**
   * Persistent, always-true facts specific to this character (including secrets unknown to others).
   */
  character_anchors?: string[];
  /**
   * Character-specific conditional behaviors or revelations. Phrased naturally as 'If/When X, then Y' statements.
   */
  character_triggers?: string[];
  /**
   * Up to 4 fixed-slot few-shot examples of voice/style/tone. Unused slots should be empty arrays or omitted. Exported sequentially, skipping empty slots.
   */
  dialog_examples?: {
    /**
     * First dialog example (optional)
     */
    example_0?: DialogLineBlock[];
    /**
     * Second dialog example (optional)
     */
    example_1?: DialogLineBlock[];
    /**
     * Third dialog example (optional)
     */
    example_2?: DialogLineBlock[];
    /**
     * Fourth dialog example (optional)
     */
    example_3?: DialogLineBlock[];
  };
  /**
   * Distilled single-sentence motivation — the engine behind all behavior.
   */
  core_drive?: string;
  /**
   * How this character specifically perceives the user's character.
   */
  user_viewpoint?: string;
  /**
   * Terms of address this character uses for the user, with optional conditions.
   */
  pet_names?: PetNameEntry[];
  /**
   * Behavioral escalation stages keyed by message-count threshold.
   */
  progression_phases?: ProgressionPhase[];
  /**
   * General past relationship patterns (complements specific relationships).
   */
  relationship_history?: string;
}
export interface AppearanceBlock {
  height?: string;
  build?: string;
  hair?: string;
  eyes?: string;
  style?: string;
  notable_features?: string[];
}
export interface PersonalityBlock {
  /**
   * Neutral core traits — LLM infers positive/negative contextually for nuance.
   */
  traits?: string[];
  motivations?: string;
  fears?: string;
  values?: string;
}
export interface RelationshipBlock {
  name: string;
  role?: string;
  notes?: string;
}
export interface SkillsBlock {
  expertise?: string[];
  hobbies?: string[];
  strengths?: string[];
  limitations?: string[];
}
export interface StoryHooksBlock {
  current_conflict?: string;
  goals?: string;
}
export interface BehaviorRulesBlock {
  /**
   * Prose hard limits (behavioral, romantic, etc.).
   */
  boundaries?: string;
  preferred_scene_types?: string[];
  disallowed_scenes?: string[];
  /**
   * Generalized romantic/sexual preferences (prose for nuance).
   */
  romantic_availability: string;
  /**
   * How the character speaks (merged communication style).
   */
  speech_style?: string;
  /**
   * Regional dialect, accent, or language quirks.
   */
  dialect_or_accent?: string;
  /**
   * Preferred response pacing (e.g., deliberate, rapid).
   */
  pacing_preference?: string;
  /**
   * Personal themes/motifs (e.g., redemption, isolation).
   */
  character_specific_themes?: string;
}
/**
 * Single line in a dialog example.
 */
export interface DialogLineBlock {
  speaker: string;
  line: string;
}
export interface CohortEntry {
  /**
   * How this person is referred to.
   */
  name: string;
  /**
   * Their function in the world or plot.
   */
  role?: string;
  /**
   * One memorable physical or behavioral trait.
   */
  signature?: string;
  /**
   * Contextual details the LLM needs to portray them consistently.
   */
  notes?: string;
}
export interface LorbookEntry {
  /**
   * The noun, phrase, or topic that triggers recall.
   */
  keyword: string;
  /**
   * What the LLM should know/recall when this keyword comes up.
   */
  content: string;
}
export interface PetNameEntry {
  /**
   * The term of address.
   */
  name: string;
  /**
   * Optional condition describing when this term is used.
   */
  trigger?: string;
}
export interface ProgressionPhase {
  /**
   * The kind of shift. Exported as '[Type] Shift' (e.g. PHASE_SHIFT). Defaults to Phase.
   */
  shift_type?: "Phase" | "Narrative" | "Tone";
  /**
   * The message count at which the LLM should begin looking for a natural opportunity to initiate this shift.
   */
  from_message: number;
  /**
   * Abandon window: if the shift has not yet occurred by this message count, stop pushing for it.
   * Does not end or undo the shift if it has already happened.
   */
  to_message?: number;
  /**
   * Prose instructions describing what changes when this shift occurs.
   */
  description: string;
}
export interface OverrideBlock {
  bot_overrides: OverrideEntry[];
  character_overrides: CharacterOverrideEntry[];
}
export interface OverrideEntry {
  field_path: string;
  value: unknown;
}
export interface CharacterOverrideEntry {
  character_id: string;
  field_path: string;
  value: unknown;
}
